# docker-compose.postgres.yml
version: '3.8'

name: postgres-stack

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    working_dir: /home/alok/postgres  # Set specific working directory
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network

networks:
  postgres_network:
    name: postgres_project_network