name: mongo-stack

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network
    ports:
      - "27017:27017"
    # restart: always  # Uncomment if you want automatic restarts

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_data: