name: postgres-stack

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    # Remove working_dir as it's not needed for postgres
    # restart: always  # Uncommented for better reliability
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

networks:
  postgres_network:
    name: postgres_project_network

# Add volumes section
volumes:
  postgres_data: